### ISSUE TITLE
Create an official, Automated Build image on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [hupili/mgcli#3]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags from git tags & branches.
Also, since documentation includes an example ```docker run``` command, this would make it run (now it fails unless the build instructions are followed). Thus the ```docker run``` command would become the canonical, no-install-needed way to run latest mgcli.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags.
Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.

Docker search command clearly displays ABs when listing images:
```
$ docker search mgcli
NAME                  DESCRIPTION   STARS     OFFICIAL   AUTOMATED
pataquets/mgcli-src   mgcli-src     0                    [OK]
pataquets/mgcli       mgcli         0                    [OK]
sukantking/mgcli                    0                    
```
Just a free Docker Hub account and a quick setup would do. Ping me if you need help.

**Comment by pataquets** [comment]
@hupili : Any feedback on this?

**Comment by hupili** [comment]
@pataquets Yes! Thanks for the suggestions. A quick survey shows that AB is the definite route to go. I was tied up with other business. Let me look into this issue during the new year break. Thanks again!

**Comment by hupili** [comment]
@pataquets Thanks again for the the pointer and previous MRs. It works better now: https://hub.docker.com/r/hupili/mgcli/

BTW, I just changed the config path to remove one initial setup step with docker. Now the `... run ...`  command should work directly.

**Comment by pataquets** [comment]
Awesome! 🎉 (sent follow-up PR)
Happy New Year!

**Comment by pataquets** [comment]
I've also deleted my images from DH to avoid users being confused, btw.
